# Generated by Django 5.1.5 on 2025-01-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=8)),
            ],
        ),
    ]
